- LICENSE
This repo was lacking a license, we follow MIT licensing for Jackal's Canine Provider Software.
> Defining MIT License 

- .github/workflows/codeql.yml
- jprov/jprovd/client_commands.go
- jprov/server/file_server.go
- jprov/server/http.go
- jprov/server/proofs.go
- jprov/server/utils.go
- jprov/utils/tx.go
Sometimes providers will refuse new deals due to a stray already being on the system even if another provider claimed it causing missed proofs.
> Fix: fid overlap

- jprov/server/proofs.go
- jprov/server/utils.go
Somehow merkleTree.New() never got updated to merkleTree.NewUsing() like the core chain it relies on. Should in the future change this all to be a library built into the core chain so that we can import it into other modules.
> Fixed all issues with proofs

- jprov/jprovd/provider_commands.go
- jprov/queue/queue.go
- jprov/strays/hand_process.go
- jprov/types/flags.go
Handling some cases where the result may be null without throwing an error. 
Some Txns would be too big and cause a timeout on the RPC, this cap should avoid that.
> Fix: SegFault & Txn Size cap

- jprov/strays/hand_process.go
`return` instead of `continue` causing strays to not get picked up as quickly as they should.
> Fix: get all strays from pile

- benchmark/bench.go
- go.mod
- go.sum
- jprov/jprovd/client_commands.go
- jprov/jprovd/init_provider.go
- jprov/jprovd/provider_commands.go
- jprov/jprovd/set_provider_ip.go
- jprov/jprovd/set_provider_keybase.go
- jprov/jprovd/set_provider_totalspace.go
- jprov/queue/queue.go
- jprov/server/file_server.go
- jprov/strays/hand_process.go
- jprov/strays/stray_manager.go
- jprov/types/flags.go
- jprov/utils/tx.go
Debating this be an option, I want providers to maintain control of their machines to the fullest, but this prevents machines from racing after the same strays which makes it better for the protocol and oftentimes the providers themselves. I think eventually, some providers would benefit from attempting to claim big files over small files, so having a few different "stray operation modes" could be really good for future-proofing. Let me know what you think.
@karnthis @BiPhan4
> feat: Randomize stray selection

- jprov/jprovd/provider_commands.go
Changing some default params so standard nodes will be less likely to all slam proofs into a single block space. This will most likely need changed again when we move the goalposts on the proving window.
> tweak: adjusting provider timings

- jprov/jprovd/client_commands.go
Issue when withdrawing, sometimes null pointer faults.
> fix: null pointer when withdraw txs fail

- jprov/server/proofs.go
- jprov/strays/hand_process.go
There seems to be a bug where providers aren't deleting files they lost due to downtime. Because of this, the hands wouldn't try to claim strays that were already on disk, I removed this as a bandage fix until we figure out why they are not removing dead files.
> fix: Providers not claiming strays they don't have

- jprov/jprovd/provider_commands.go
- jprov/queue/queue.go
- jprov/server/proofs.go
- jprov/types/flags.go
I updated my personal provider to use main as at latest commit--interval improvement. Timeout errors still occur, although much more spread out in time. 
Per source code, a tendermint node will wait 10 seconds before removing a transaction from its mempool and returning the time out error. 
Even though we are spreading out the periods during which our proofs are committed, we are still overloading our tendermint nodes while we are committing proofs.
I opine this is the current problematic chain of events:
1. postProofs() can add proof msgs to the queue very fast, so much so that when listenOnce() is called, there is a possibility that the queue has 50+ proof msgs--which is very likely if a provider has many files.
2. Based on our default 'max-msg-size', the maximum number of msgs per …
> sleep for 1 second before adding another proof to queue

- jprov/server/http.go
- jprov/types/types.go
Returns chain-id in the version response to check which network the provider is running on.
> API: chain-id in the version response

- go.mod
- go.sum
- jprov/jprovd/provider_commands.go
- jprov/jprovd/root.go
Providers can now run [Blanket](https://github.com/JackalLabs/blanket) straight from their provider with no additional installation. This allows them to monitor their provider with a terminal GUI in realtime.
> feat: integrate monitoring

- jprov/server/file_server.go
- jprov/utils/network.go
Sprintfs use a ton of memory right now, switching to string builders should solve this.
> Removing more Sprintfs

- jprov/jprovd/provider_commands.go
With the new stray improvements, providers claim strays insanely quick, this is causing some issues on lower-end machines and as such we're lowering the default for the uninformed. Beefier providers can up this count with the flag.
> Fix: Lowering threads

- jprov/utils/network.go
Some providers only accept downloads from browsers because of their reverse proxy, instead of fighting this, let's see about fixing this from a provider level.
> Fix: Stray Headers

- jprov/server/attestation.go
- jprov/server/proofs.go
Proofs are taking longer now due to attestation form creation, to combat this, we multi-thread the attestation request.
> Fix: Sequential Proof Slowdown

- jprov/server/file_server.go
- jprov/testutils/testFile.go
Adding new error catching, does this mess up JJS @karnthis ?
> API: better cid and fid error handling

- jprov/jprovd/provider_commands.go
fix `flag accessed but not defined: max-misses` error when `jprovd prune` is used
> fix flag max-misses not defined error

- jprov/server/file_server.go
- jprov/server/query.go
From Brochain: 
> Pruning resumes. It seems that if the provider cannot connect to an RPC for whatever reason, it doesn't try again, it exits.
So we make sure pruning never fails while pining the RPC node unless it's the very first attempt.
We also filter out active deals that aren't ours as we go rather than after to make sure our memory usage doesn't spike like crazy.
> Fix prune time + node read issues

- jprov/server/file_server.go
- jprov/server/proofs.go
- jprov/server/query.go
- jprov/server/utils.go
- jprov/types/state.go
It'll simply keep on retrying to post proof when rpc is down.
The files won't be marked for deletion.
> prevent files from burning when rpc is down
